# Generated by Django 5.1.6 on 2025-03-08 13:35

import core.user.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_user", "0005_user_posts_liked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to=core.user.models.user_directory_path
            ),
        ),
    ]
