name: Build, Test and Deploy Postagram backend

on:
  push:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Injecting environment vars
      run: |
        cat <<EOF > .env
        SECRET_KEY=test_foo
        DATABASE_NAME=test_coredb
        DATABASE_USER=test_core
        DATABASE_PASSWORD=12345678
        DATABASE_HOST=test_postagram_db
        DATABASE_PORT=5432
        POSTGRES_USER=test_core
        POSTGRES_PASSWORD=12345678
        POSTGRES_DB=test_coredb
        ENV=TESTING
        DJANGO_ALLOWED_HOSTS=0.0.0.0,localhost
        EOF

    - name: Building Docker containers
      run: |
        docker-compose up -d --build
        docker-compose logs

    - name: Running Tests inside Docker containers
      run: |
        docker-compose run --rm api pytest

  deploy:
    name: Deploying on EC2 via SSH
    if: ${{ github.event_name == 'push' }}
    needs: [build-test]
    runs-on: ubuntu-latest
    steps:
    - name: Deploying Application on EC2
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.SSH_EC2_IP }}
        username: ${{ secrets.SSH_EC2_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ~/.scripts
          ./docker-ec2-deploy.sh
